import type { Ator, Caso } from './types';

export const atores: Ator[] = [
  { id: 'op',     nome: 'Operador',         papel: 'Humano · usuário do Genesis',    cor: 'info'   },
  { id: 'genesis', nome: 'Genesis',          papel: 'Cérebro de mensageria',          cor: 'purple' },
  { id: 'polly',   nome: 'messaging-service', papel: 'Transporte multi-provider',     cor: 'purple' },
  { id: 'meta',    nome: 'Meta WhatsApp',    papel: 'Provider externo',               cor: 'info'   },
];

export const casos: Caso[] = [
  {
    id: 'c1',
    ordem: 1,
    atorId: 'op',
    nome: 'Clica em "Disparar campanha"',
    passo: 'Operador termina o setup da campanha (template + destinatários) e clica no botão Disparar no frontend.',
    oQueAcontece: 'Frontend faz HTTP POST /api/campanhas/{id}/disparar. Recebe 202 imediato. O envio em si acontece em background.',
    porQueImporta: 'É o único ponto manual do fluxo. Tudo depois é automático.',
  },
  {
    id: 'c2',
    ordem: 2,
    atorId: 'genesis',
    nome: 'Valida campanha e enfileira',
    passo: 'Backend Genesis valida: campanha tem template? Tem destinatários? Status é rascunho/enviando? Publica 1 mensagem na fila campaigns.dispatch.',
    oQueAcontece: 'INSERT log + UPDATE campanha.status="na_fila" + send_message ao Service Bus. Retorna 202 pro frontend.',
    porQueImporta: 'Validação aqui evita lixo na fila. Garante que só campanha completa entra no pipeline.',
  },
  {
    id: 'c3',
    ordem: 3,
    atorId: 'genesis',
    nome: 'Dispatcher pega da fila',
    passo: 'Worker dispatcher (App Service dedicado) consome a fila. Lê destinatários da campanha em batches de 500.',
    oQueAcontece: 'SELECT campanha_destinatarios JOIN contato WHERE status="pendente". Não precisa carregar 10k de uma vez.',
    porQueImporta: 'Sessão curta no banco. Streaming. Aguenta campanhas grandes sem timeout.',
  },
  {
    id: 'c4',
    ordem: 4,
    atorId: 'genesis',
    nome: 'Renderiza variáveis do template',
    passo: 'Pra cada destinatário, substitui __nome__ → "Maria", __email__ → "...", __nome_abreviado__ → primeiro nome.',
    oQueAcontece: 'Lê contato.nome/email/telefone do CRM e monta o objeto template_components no formato Meta Graph API.',
    porQueImporta: 'Genesis é dono do CRM. messaging-service NÃO conhece esses campos. Renderização tem que sair daqui.',
  },
  {
    id: 'c5',
    ordem: 5,
    atorId: 'genesis',
    nome: 'Decide canal e janela 24h',
    passo: 'Olha preferência do contato (WA/SMS/IG). Verifica se conversa está dentro da janela 24h.',
    oQueAcontece: 'Se dentro de 24h: pode mandar texto livre. Fora: obrigatório template HSM (regra Meta). Define channel + template_name.',
    porQueImporta: 'Regra de negócio de mensageria. Polly só executa o transporte — não decide janela.',
  },
  {
    id: 'c6',
    ordem: 6,
    atorId: 'genesis',
    nome: 'Publica em messaging.send',
    passo: 'Genesis monta o payload final com idempotency_key único por destinatário e publica na fila do messaging-service.',
    oQueAcontece: 'send_message com { channel, to: "+5511...", template_name, template_components, from_app, tenant_id, idempotency_key }.',
    porQueImporta: 'Idempotency_key garante que se a msg cair 2× (redelivery), Polly não dispara WhatsApp duplicado.',
  },
  {
    id: 'c7',
    ordem: 7,
    atorId: 'polly',
    nome: 'Verifica idempotência',
    passo: 'messaging-service pega a msg. Antes de fazer qualquer coisa, busca no banco se (from_app, idempotency_key) já existe.',
    oQueAcontece: 'SELECT messages WHERE from_app="genesis" AND idempotency_key=X. Se existir, retorna o registro antigo SEM reenviar.',
    porQueImporta: 'Garantia hard de não-duplicação. UNIQUE constraint no banco impede até race condition.',
  },
  {
    id: 'c8',
    ordem: 8,
    atorId: 'polly',
    nome: 'Aplica rate limit + circuit breaker',
    passo: 'Verifica leaky bucket por (tenant + provider). Verifica estado do circuit breaker do Meta.',
    oQueAcontece: 'Se circuit OPEN: fail-fast sem chamar Meta. Se rate limit estourado: scheduled message pro futuro. Caso contrário: prossegue.',
    porQueImporta: 'Protege Meta API de overload e protege seu tenant de ficar bloqueado pela Meta.',
  },
  {
    id: 'c9',
    ordem: 9,
    atorId: 'meta',
    nome: 'Envia via Meta Cloud API',
    passo: 'messaging-service faz HTTP POST graph.facebook.com/v19.0/{phone_id}/messages com template + parameters.',
    oQueAcontece: 'Meta valida template aprovado, envia ao celular do destinatário. Retorna { messages: [{ id: "wamid.XYZ" }] }.',
    porQueImporta: 'Único ponto de contato com a Meta. Toda comunicação WhatsApp do ecossistema passa aqui.',
  },
  {
    id: 'c10',
    ordem: 10,
    atorId: 'polly',
    nome: 'Persiste e publica em status',
    passo: 'messaging-service grava { status: "sent", wamid, sent_at } na tabela messages. Publica evento no tópico messaging.status.',
    oQueAcontece: 'INSERT/UPDATE messages + publish ao topic. Outros consumers (Genesis, BI futuro) recebem o evento.',
    porQueImporta: 'Pub/sub permite múltiplos consumers. BI pode ler o mesmo evento sem o Genesis saber.',
  },
  {
    id: 'c11',
    ordem: 11,
    atorId: 'genesis',
    nome: 'Status worker atualiza conversa',
    passo: 'Genesis Status Worker consome messaging.status. Atualiza mensagem.status, wamid e contadores da campanha. Broadcast WebSocket.',
    oQueAcontece: 'UPDATE mensagens SET status="enviada" WHERE wamid=X. UPDATE campanhas SET enviadas=enviadas+1. ws.broadcast(tenant_id, evento).',
    porQueImporta: 'Operador vê na tela em tempo real: 487/1000 enviadas. Sem polling, sem refresh.',
  },
  {
    id: 'c12',
    ordem: 12,
    atorId: 'meta',
    nome: 'Callback delivered/read',
    passo: 'Quando o celular do destinatário entrega a msg, Meta dispara webhook de status pro messaging-service.',
    oQueAcontece: 'POST /webhooks/whatsapp/status com { wamid, status: "delivered" }. Mais tarde, mesmo wamid com status="read" se o contato abrir.',
    porQueImporta: 'Hoje você não tem isso. Operador só vê "enviada", nunca "entregue" ou "lida".',
  },
  {
    id: 'c13',
    ordem: 13,
    atorId: 'polly',
    nome: 'Republica delivered/read',
    passo: 'messaging-service normaliza o callback Meta/Twilio/IG num formato comum e publica em messaging.status.',
    oQueAcontece: 'Atualiza tabela messages local + publish ao topic. Genesis e BI recebem juntos.',
    porQueImporta: 'Mesmo tópico do "sent" do passo 10. Genesis só consome 1 tópico, normalizado, multi-canal.',
  },
  {
    id: 'c14',
    ordem: 14,
    atorId: 'genesis',
    nome: 'Atualiza badges na UI',
    passo: 'Status worker recebe delivered/read e atualiza ✓✓ azul na conversa. Frontend pisca via WebSocket.',
    oQueAcontece: 'UPDATE mensagens SET status="lida". Broadcast pro frontend que renderiza o check duplo azul.',
    porQueImporta: 'É o que o usuário VÊ. Fechou o ciclo: clicou no botão (passo 1) → viu o check azul (passo 14).',
  },
];
